apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
  namespace: default
spec:
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer